export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';
export const MOVIE_LIST_RESET = 'MOVIE_LIST_RESET';

export const MOVIE_ADD_REQUEST = 'MOVIE_ADD_REQUEST';
export const MOVIE_ADD_SUCCESS = 'MOVIE_ADD_SUCCESS';
export const MOVIE_ADD_FAIL = 'MOVIE_ADD_FAIL';
export const MOVIE_ADD_RESET = 'MOVIE_ADD_RESET';

export const MOVIE_UPDATE_REQUEST = 'MOVIE_UPDATE_REQUEST';
export const MOVIE_UPDATE_SUCCESS = 'MOVIE_UPDATE_SUCCESS';
export const MOVIE_UPDATE_FAIL = 'MOVIE_UPDATE_FAIL';
export const MOVIE_UPDATE_RESET = 'MOVIE_UPDATE_RESET';

export const MOVIE_DELETE_REQUEST = 'MOVIE_DELETE_REQUEST';
export const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
export const MOVIE_DELETE_FAIL = 'MOVIE_DELETE_FAIL';
export const MOVIE_DELETE_RESET = 'MOVIE_DELETE_RESET';

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL';
export const MOVIE_DETAILS_RESET = 'MOVIE_DETAILS_RESET';

export const NOW_LIST_REQUEST = 'NOW_LIST_REQUEST';
export const NOW_LIST_SUCCESS = 'NOW_LIST_SUCCESS';
export const NOW_LIST_FAIL = 'NOW_LIST_FAIL';

export const COMING_LIST_REQUEST = 'COMING_LIST_REQUEST';
export const COMING_LIST_SUCCESS = 'COMING_LIST_SUCCESS';
export const COMING_LIST_FAIL = 'COMING_LIST_FAIL';

export const MOVIE_UPLOAD_REQUEST = 'MOVIE_UPLOAD_REQUEST';
export const MOVIE_UPLOAD_SUCCESS = 'MOVIE_UPLOAD_SUCCESS';
export const MOVIE_UPLOAD_FAIL = 'MOVIE_UPLOAD_FAIL';
export const MOVIE_UPLOAD_RESET = 'MOVIE_UPLOAD_RESET';
