export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';
export const MOVIE_LIST_RESET = 'MOVIE_LIST_RESET';

export const MOVIE_ADD_REQUEST = 'MOVIE_ADD_REQUEST';
export const MOVIE_ADD_SUCCESS = 'MOVIE_ADD_SUCCESS';
export const MOVIE_ADD_FAIL = 'MOVIE_ADD_FAIL';
export const MOVIE_ADD_RESET = 'MOVIE_ADD_RESET';

export const MOVIE_UPDATE_REQUEST = 'MOVIE_UPDATE_REQUEST';
export const MOVIE_UPDATE_SUCCESS = 'MOVIE_UPDATE_SUCCESS';
export const MOVIE_UPDATE_FAIL = 'MOVIE_UPDATE_FAIL';
export const MOVIE_UPDATE_RESET = 'MOVIE_UPDATE_RESET';

export const MOVIE_DELETE_REQUEST = 'MOVIE_DELETE_REQUEST';
export const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
export const MOVIE_DELETE_FAIL = 'MOVIE_DELETE_FAIL';
export const MOVIE_DELETE_RESET = 'MOVIE_DELETE_RESET';

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL';
export const MOVIE_DETAILS_RESET = 'MOVIE_DETAILS_RESET';

export const NOW_LIST_REQUEST = 'NOW_LIST_REQUEST';
export const NOW_LIST_SUCCESS = 'NOW_LIST_SUCCESS';
export const NOW_LIST_FAIL = 'NOW_LIST_FAIL';

export const COMING_LIST_REQUEST = 'COMING_LIST_REQUEST';
export const COMING_LIST_SUCCESS = 'COMING_LIST_SUCCESS';
export const COMING_LIST_FAIL = 'COMING_LIST_FAIL';

export const MOVIE_UPLOAD_REQUEST = 'MOVIE_UPLOAD_REQUEST';
export const MOVIE_UPLOAD_SUCCESS = 'MOVIE_UPLOAD_SUCCESS';
export const MOVIE_UPLOAD_FAIL = 'MOVIE_UPLOAD_FAIL';
export const MOVIE_UPLOAD_RESET = 'MOVIE_UPLOAD_RESET';

export const MOVIE_SEAT_REQUEST = 'MOVIE_SEAT_REQUEST';
export const MOVIE_SEAT_SUCCESS = 'MOVIE_SEAT_SUCCESS';
export const MOVIE_SEAT_FAIL = 'MOVIE_SEAT_FAIL';
export const MOVIE_SEAT_RESET = 'MOVIE_SEAT_RESET';

export const MOVIE_SEAT_UPDATE_REQUEST = 'MOVIE_SEAT_UPDATE_REQUEST';
export const MOVIE_SEAT_UPDATE_SUCCESS = 'MOVIE_SEAT_UPDATE_SUCCESS';
export const MOVIE_SEAT_UPDATE_FAIL = 'MOVIE_SEAT_UPDATE_FAIL';
export const MOVIE_SEAT_UPDATE_RESET = 'MOVIE_SEAT_UPDATE_RESET';

export const MOVIE_SEAT_RESERVE_REQUEST = 'MOVIE_SEAT_RESERVE_REQUEST';
export const MOVIE_SEAT_RESERVE_SUCCESS = 'MOVIE_SEAT_RESERVE_SUCCESS';
export const MOVIE_SEAT_RESERVE_FAIL = 'MOVIE_SEAT_RESERVE_FAIL';
export const MOVIE_SEAT_RESERVE_RESET = 'MOVIE_SEAT_RESERVE_RESET';

export const MOVIE_CHECKOUT_REQUEST = 'MOVIE_CHECKOUT_REQUEST';
export const MOVIE_CHECKOUT_SUCCESS = 'MOVIE_CHECKOUT_SUCCESS';
export const MOVIE_CHECKOUT_FAIL = 'MOVIE_CHECKOUT_FAIL';
export const MOVIE_CHECKOUT_RESET = 'MOVIE_CHECKOUT_RESET';

export const MOVIE_CHECKOUT_TOTAL_REQUEST = 'MOVIE_CHECKOUT_TOTAL_REQUEST';
export const MOVIE_CHECKOUT_TOTAL_SUCCESS = 'MOVIE_CHECKOUT_TOTAL_SUCCESS';
export const MOVIE_CHECKOUT_TOTAL_FAIL = 'MOVIE_CHECKOUT_TOTAL_FAIL';
export const MOVIE_CHECKOUT_TOTAL_RESET = 'MOVIE_CHECKOUT_TOTAL_RESET';

export const DIALOG_REQUEST = 'DIALOG_REQUEST';
export const DIALOG_SUCCESS = 'DIALOG_SUCCESS';
export const DIALOG_FAIL = 'DIALOG_FAIL';
export const DIALOG_RESET = 'DIALOG_RESET';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL';
export const GET_ORDER_RESET = 'GET_ORDER_RESET';

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL';
export const GET_MOVIE_RESET = 'GET_MOVIE_RESET';

export const LIST_ORDER_REQUEST = 'LIST_ORDER_REQUEST';
export const LIST_ORDER_SUCCESS = 'LIST_ORDER_SUCCESS';
export const LIST_ORDER_FAIL = 'LIST_ORDER_FAIL';
export const LIST_ORDER_RESET = 'LIST_ORDER_RESET';

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';
export const ORDER_DELETE_RESET = 'ORDER_DELETE_RESET';
